name: event_frog
description: A framework for making dart_frog web servers using event_db
version: 0.1.3
repository: https://github.com/VHCBlade/event_frog

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dart_frog: ^0.3.0

  event_authentication: ^0.1.3
  event_bloc: ^4.2.0
  event_db: ^0.1.11

  tuple: ^2.0.0

dev_dependencies:
  event_bloc_tester: ^0.1.4

  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^4.0.0
